### ISSUE TITLE
Active Directory

### ISSUE THREAD

**Issue by AlroneRhyn** [babelouest/glewlwyd#31]
Hi !
I wanted to try your OAuth2 server but failed to configure Active Directory settings, i got this message `Glewlwyd ERROR: Error ldap search: Operations error` when i want to Grant access once i'am connected.
Do the admin has to be be into the ldap ? Is there any other debug ldap output that i can get ?

What am i missing ? Do you need any other information ?

Thanks a lot,

**Comment by babelouest** [comment]
Hello,

It looks like a configuration problem. To manipulate the users and clients in the LDAP/AD, Glewlwyd needs to connect with a user that has access to the `base_search_*` locations, like an operator.
You must specify this user credentials in the `bind_dn/bind_password` parameters: https://github.com/babelouest/glewlwyd/blob/master/glewlwyd.conf.sample#L167

If you want to be able to modify the LDAP users, the operator user must have write access to the properties you want to modify, but if you use it in read-only, the operator can have a read-only access too.

**Comment by AlroneRhyn** [comment]
Hi,
I should have got it right, if my bind_user is not right, here is the error message `Glewlwyd ERROR: Error binding to ldap server mode (null): Invalid credentials`. It seems that my ldap connect conf is right but i cannot "Grant Access" (and i don't relly know what does that mean).
![capture d ecran 2017-12-18 a 10 23 31](https://user-images.githubusercontent.com/8383459/34098707-95529262-e3dd-11e7-93e3-e86abab1edd0.png)

Thanks

**Comment by babelouest** [comment]
I would need more information but I'm guessing you have problems in your configuration. The scope values in the LDAP config for a user is determined by the `scope_property_user_read` value: https://github.com/babelouest/glewlwyd/blob/master/glewlwyd.conf.sample#L174

You must set this value with a valid LDAP property that will contain the exact values of the scopes the LDAP user will have access to. For example, if you set this value to `o`, your user must have the values `g_profile` and `g_admin` in the LDAP `o` property to be able to connect to Glewlwyd administration page.

Also, you can check your Glewlwyd log messages for more information about the `Error granting scope`.

Let me know how it goes.

**Comment by babelouest** [comment]
Hello @AlroneRhyn , any update on your LDAP problems?

**Comment by babelouest** [comment]
@AlroneRhyn , any clue?

**Comment by AlroneRhyn** [comment]
@babelouest Hi, i will put my mind into it again next week and give you some update, i will apply RTFM to myself too.
Thanks

**Comment by babelouest** [comment]
Hello @Peter2121 ,

I've recently made some improvements in the `INSTALL.md` file concerning LDAP config, maybe some things will be more clear: https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#ldap-authentication

On thing that will be added to the documentation too is that in order to connect to a fresh Glewlwyd install with LDAP, you must have one user with the values `g_admin` and `g_profile` in its `o` LDAP property, so this user will be able to connect to the administrator page.

Since I don't have any AD around to test Glewlwyd with, I don't know the differences so thank you for pointing me what's not working with AD.
Concerning the `int scope = LDAP_SCOPE_ONELEVEL;`, what is the correct value for you? I will make small corrections to avoid this.

**Comment by Peter2121** [comment]
@babelouest 
Thanks for your answer.
I used the updated `INSTALL.md`, unfortunately it is not clear for me.
As about scope - one should be able to choose between `LDAP_SCOPE_ONELEVEL` and `LDAP_SCOPE_SUBTREE` configuring LDAP in glewlwyd.conf

**Comment by babelouest** [comment]
@Peter2121 ,

OK for the scope, I'll add an option to choose between `LDAP_SCOPE_BASE`, `LDAP_SCOPE_ONELEVEL`, `LDAP_SCOPE_SUBTREE` and `LDAP_SCOPE_CHILDREN` then, according to `ldap_search_s(3)`.

But I still need more feedback on the `INSTALL.md` that is not clear for you. What is not clear more specifically?

**Comment by Peter2121** [comment]
I think that you need to provide a WORKING example of AD configuration. Such example could contain database initialization script(s), configuration file and ldif file of admin user.
Now I changed the place of admin user and replaced 'o' with 'cn' in config file, so using g_admin as username (so g_admin is in 'cn' attribute too) it should work, but it does not.

**Comment by babelouest** [comment]
Again, I don't have any AD at my disposal, so providing specific AD configuration is quite difficult for me without help. Are you able to provide me the help required to update the documentation with AD?

Also, when I say I need more feedback, I mean more than "it does not work". What does not work? Can you provide logs? Can you provide your config file without the secret data of course? Can you describe the commands you're using? Without more data I can't be of real help I'm afraid.

**Comment by Peter2121** [comment]
I'll prepare such elements for you, it takes some time as I'm already on another project now.
Thanks for your reactivity!

**Comment by Peter2121** [comment]
@babelouest, please, can you explain (here or in the documents) the _concepts_ of `g_admin` and `g_profile` in LDAP configuration?

**Comment by babelouest** [comment]
`g_admin` and `g_profile` are OAuth2 scopes, they can be seen as control access levels. When a users connects to an OAuth2 authentication server, he or she has to ask for one or more scopes. If the authentication is granted by the OAuth2 server, then the server checks what scopes can be granted to the user. Then the OAuth2 server sends back a token specifying the scopes granted which is all or a subset of the scopes asked.
In the end of the authentication process, the resource can grant access to resources or not according to the scopes that have been granted.
The whole OAuth2 standard is defined in the [RFC 6749](https://tools.ietf.org/html/rfc6749).

In a higher level, this means something like this. This is a very simple use case to explain the concept of scopes:
- Bob wants to access the company addressbook
- The addressbook application he uses redirects him to the OAuth2 server asking grant access to the scopes `addressbook_guest` and `addressbook_admin`
- The OAuth2 server finds out Bob has access to the scope `addressbook_guest` only since he's a low-level user
- The OAuth2 server redirects to the addressbook application with a token giving access to `addressbook_guest`
- Then Bob can access to the addressbook data, but if he tries to update a card, it will be forbidden.

In Glewlwyd case when you try to access to the admin application to manage users, clients, scopes, etc. Your user needs to have the scope `g_admin`. If you want the user to access its own data (login, e-mail, password and display name), your user needs to have the scope `g_profile`.

Here is the glewlwyd.conf file authentication block:

```
authentication =
{
   database_auth = true

   ldap_auth     = true
   uri           = "ldap://ldapserver"
   bind_dn       = "cn=operator,dc=glewlwyd,dc=domain"
   bind_passwd   = "xxx"

   base_search_user             = "ou=user,dc=glewlwyd,dc=domain"
# Read parameters
   filter_user_read             = "objectClass=inetOrgPerson"
   login_property_user_read     = "cn"
   scope_property_user_read     = "o"
   email_property_user_read     = "mail"
   name_property_user_read      = "sn"
   additional_property_value_read = "postalCode"
# Write parameters
   ldap_user_write               = true
   rdn_property_user_write       = "cn"
   login_property_user_write     = "cn"
   scope_property_user_write     = "o"
   email_property_user_write     = "mail"
   additional_property_value_write = "postalCode"
   name_property_user_write      = "sn"
   password_property_user_write  = "userPassword"
   password_algorithm_user_write = "SSHA"
   object_class_user_write       = "top,person,organizationalPerson,inetOrgPerson"

   base_search_client             = "ou=client,dc=glewlwyd,dc=domain"
# Read parameters
   filter_client_read                = "objectClass=inetOrgPerson"
   client_id_property_client_read    = "cn"
   scope_property_client_read        = "o"
   name_property_client_read         = "sn"
   description_property_client_read  = "description"
   redirect_uri_property_client_read = "labeledURI"
   confidential_property_client_read = "employeeType"
# Write parameters
   ldap_client_write                  = true
   rdn_property_client_write          = "cn"
   client_id_property_client_write    = "cn"
   scope_property_client_write        = "o"
   name_property_client_write         = "sn"
   description_property_client_write  = "description"
   redirect_uri_property_client_write = "labeledURI"
   password_property_client_write     = "userPassword"
   confidential_property_client_write = "employeeType"
   password_algorithm_client_write    = "SSHA"
   object_class_client_write          = "top,person,organizationalPerson,inetOrgPerson"
}
```

Here are 2 example LDAP users extracted from the OpenLDAP server:

```
# bob, user
dn: cn=bob,ou=user,dc=glewlwyd,dc=domain
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
cn: bob
sn: Bob the low-level guy
mail: bob@glewlwyd.domain
o: g_profile
userPassword:: xxx
```

```
# alice, super user
dn: cn=alice,ou=user,dc=glewlwyd,dc=domain
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
cn: alice
sn: Alice the high-level boss
mail: alice@glewlwyd.domain
o: g_admin
o: g_profile
userPassword:: xxx
```

**Comment by babelouest** [comment]
@Peter2121 , ldap search scope is now in the glewlwyd.conf file:
```
   search_scope  = "subtree" # mandatory, scope of the LDAP search, values available are "onelevel", "subtree" or "children", see the manpage ldap_search(3) for more information
```

Can you check this out in the master branch?

**Comment by Peter2121** [comment]
@babelouest 
Thanks a lot for your reactivity!!
As about g_profile and g_admin - I understand better now, but obviously it cannot work like this in AD environment. The attribute 'o' is not used and difficult to access, and the security roles are managed normally using groups membership. So, it seems that the simplest way to integrate _glewlwyd_ in an existing environment could be the method of using 'memberOf' attribute for searching scopes membership. The problem is that it contains full DNs of groups, like `CN=Administrators,CN=Builtin,DC=domain,DC=local`, so the direct searching of attribute like `Administrators` (g_admin in your example) should be replaced by searching of pattern, like `*Administrators*`.

There is one question that is still not clear. We find in the conf file:
```
admin_scope="g_admin"
profile_scope="g_profile"
```
In the same time we find in SQL initialization script:
```
INSERT INTO g_scope (gs_name, gs_description) VALUES ('g_admin', 'Glewlwyd admin scope');
INSERT INTO g_scope (gs_name, gs_description) VALUES ('g_profile', 'Glewlwyd profile scope');
```
What part is responsible for LDAP attributes searching, and what part - for Oauth2 scopes?
For example, if I want to search for `Administrators` in `memberOf` attribute, and use the accounts with such group present as members of `g_admin` scope - how should I proceed?

**Comment by babelouest** [comment]
In your case, I don't think you should bind Glewlwyd's scopes that hard with your access roles.
To make it easier, you could set the scopes values in a LDAP property you don't usually use and manually update this property. In my case, since I use the `InetOrgPerson` class, I could use one of the many unused properties to store OAuth2 data. If you can store the OAuth2 scope values in an unused LDAP property, it may be easier for you.
The additional property was recently added so LDAP groups can be more easily managed: #26 .

If you want to change the LDAP scope search pattern in the code, you can too but that's not the solution I would go for.

The properties `admin_scope` and `profile_scope` in the conf file are here to set the name of those scopes. If you update these values, you must also update the sql script and add the `admin_scope` value in the scopes available for the admins, otherwise you wouldn't be able to connect to the administrator page.
You can change the `admin_scope` value to `Administrators`, so only the LDAP users with that value in the specified property will be able to connect to Glewlwyd's admin page.

**Comment by Peter2121** [comment]
> To make it easier, you could set the scopes values in a LDAP property you don't usually use and manually update this property

Imagine an AD with 1000+ users where you want to add Oauth2 authentication. So, one should modify all accounts to add a possibility to login using Oauth2? Sure, it's possible to do such modification with a script, but logically, using an existing system with user groups seems to be more simple. The additional property mentioned in #26 goes in the same direction ;)

**Comment by babelouest** [comment]
How about adding a config value like `scope_match` with the values `equals` or `contains` for example, so if the scope required can be valid if it is contained in the scope property?

**Comment by Peter2121** [comment]
> How about adding a config value like scope_match with the values equals or contains for example, so if the scope required can be valid if it is contained in the scope property?
Looks very promising :)
It could permit using `memberOf` field for scopes defining.

**Comment by babelouest** [comment]
I'll make the patch like this then, be careful that if you use the new config value like this `scope_match = contains`, it will look for the scope value in all the memberOf property.

Although if your memberOf value is like `CN=Administrators,CN=Builtin,DC=mySkateboardCompany,DC=local` and you look for the scope `Skateboard`, it will give the access to all users for the scope `Skateboard` because you didn't think too hard about your scope values. So be very careful with that!

**Comment by Peter2121** [comment]
> I'll make the patch like this then, be careful that if you use the new config value like this scope_match = contains, it will look for the scope value in all the memberOf property.

Yes, I understand that `scope_match = contains` is not a perfect solution, it **can** produce some side effects. But IMHO it's better than massive playing with some unused attributes.
BTW, can you build a package with these patches, please? I installed Debian testing to play with glewlwyd so I used binary release from Debian repository.

**Comment by babelouest** [comment]
I will make Debian packages but not right now, I have some changes to make to the underlying libraries first.
But you can build your own Debian package using the CMake script:

```shell
$ mkdir glewlwyd/build
$ cd glewlwyd/build
$ cmake ..
$ make package
```

Then a glewlwyd_*.deb will be created in your `build` folder so you can deploy it.

**Comment by babelouest** [comment]
@Peter2121 , @AlroneRhyn , I've added the config properties `scope_property_user_match` and `scope_property_client_match` to help using the `memberOf` AD property to match OAuth2 scopes, it's in the master branch.

Can you test this new feature in your AD environment?

**Comment by Peter2121** [comment]
@babelouest,
Thanks a lot for the modifications, I'll be able to test the new version the next week.

**Comment by babelouest** [comment]
@Peter2121 , I've just released Glewlwyd 1.4.0 with the recent changes, the Debian packages are available too. Let me know if you have issues.

**Comment by Peter2121** [comment]
I have the problem installing the dependency from glewlwyd-full_1.4.0_Debian_buster_x86_64.tar.gz:
```
# gdebi libyder_1.3.1_Debian_buster_x86_64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done
Traceback (most recent call last):
  File "/usr/bin/gdebi", line 86, in <module>
    if not debi.open(args[0]):
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 88, in open
    if not self._deb.check():
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 530, in check
    if not self._satisfy_depends(self.depends):
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 304, in depends
    apt_pkg.parse_depends(self._sections[key], False))
ValueError: Problem Parsing Dependency
```

**Comment by babelouest** [comment]
You need to install `libsystemd-dev` now, sorry, I forgot about that.

**Comment by babelouest** [comment]
I answer to myself, my answer on top may be wrong. Can you try installing libyder with apt?

**Comment by Peter2121** [comment]
```
# apt install libyder2.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
libyder2.0 is already the newest version (1.1.1-1).
libyder2.0 set to manually installed.

```

**Comment by babelouest** [comment]
My bad, I'm not fully woken up yet, I meant dpkg, not apt...

`dpkg -i libyder_1.3.1_Debian_buster_x86_64.deb`

**Comment by Peter2121** [comment]
```
# dpkg -i libyder_1.3.1_Debian_buster_x86_64.deb
dpkg: error processing archive libyder_1.3.1_Debian_buster_x86_64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 6 package 'libyder':
 'Depends' field, syntax error after reference to package 'liborcania'
Errors were encountered while processing:
 libyder_1.3.1_Debian_buster_x86_64.deb

```

**Comment by babelouest** [comment]
I think I fixed libyder now, it was a dependecy typo.
Can you try to install the new libyder package in the [Realease 1.3.2](https://github.com/babelouest/yder/releases/tag/v1.3.2)?
Then you should be able to install ulfius, hoel ang glewlwyd.

**Comment by Peter2121** [comment]
Library libyder version is not correct in previous releases - 1.2.0.
The glewlwyd 1.4.0 wants 1.3 :
```
# glewlwyd --config-file=/etc/glewlwyd/glewlwyd.conf
glewlwyd: error while loading shared libraries: libyder.so.1.3: cannot open shared object file: No such file or directory
```

**Comment by babelouest** [comment]
Should be fixed now, can you retry installing [Glewlwyd 1.4.0](https://github.com/babelouest/glewlwyd/releases/tag/v1.4.0)?

**Comment by Peter2121** [comment]
OK, indeed, it is fixed.
I cannot get it working though :(
Firstly, when I click on "Login" at `http://<myip>:4593/app/index.html` it tries to search `(&(objectClass=organizationalPerson)(cn=g_admin))` in `wholeSubtree` of my `base_search_user`. Why?
OK, I moved the group `g_admin` to another OU and added the user `g_admin` here, his `memberOf` contains `g_admin` as he is a member of this group. The result of LDAP query is `CN=g_admin,CN=Users,DC=domain,DC=local`, the `memberOf` attribute returned is `CN=g_admin,OU=Objets Test,DC=domain,DC=local`. But I receive "You are not authorized to connect to this application" error.
My config is:
```
search_scope             = "subtree"
filter_user_read               = "objectClass=organizationalPerson"
login_property_user_read       = "cn"
scope_property_user_read       = "memberOf"
email_property_user_read       = "mail"
name_property_user_read        = "sn"
scope_property_user_match      = "contains"
additional_property_value_read = "memberOf"
```
What did I missed?

**Comment by babelouest** [comment]
Let's say the user called `Robert The Bruce` wants to log in Glewlwyd admin page, his login is `bob` and his password is `password`, he is allowed to access the scope `g_admin` because he's member of the group `cn=g_admin,dc=domain,dc=local`, so he has a LDAP entry `memberOf` with a value `cn=g_admin,dc=domain,dc=local`.

The LDAP process is the following:
1- Glewlwyd searches for a LDAP entry based on the login and the filter given with a search pattern like `(&(objectClass=organizationalPerson)(cn=bob))` in the Base DB specified. If a user is found, it returns the full DN of the ldap entry, like `cn=bob,,cn=users,dc=domain,dc=local`, `sn=Robert The Bruce,cn=users,dc=domain,dc=local` or `uid=1234567890abcdef,cn=users,dc=domain,dc=local`, for example.
https://github.com/babelouest/glewlwyd/blob/master/src/user.c#L637

2- Then Glewlwyd tests the LDAP password given with the full DN previously retrieved
https://github.com/babelouest/glewlwyd/blob/master/src/user.c#L647

3- If the login is succesfull, then Glewlwyd searches for an entry in the property `memberOf` with the pattern `*g_admin*`.
https://github.com/babelouest/glewlwyd/blob/master/src/user.c#L819

4- If a `memberOf` entry is found, Glewlwyd returns login succesfull. If any of the steps above is false, Glewlwyd stops checking and returns login unauthorized.

I don't know yet where your problem would be yet.
First you can change the config value `admin_scope` from `g_admin` to the name of the admin group you use, like `Administrators` (case sensitive!).
Also, check the value `login_property_user_read` to match your login property, or at least a property that can be used as login, like `cn`, `uid`, `login`, whatever fits your LDAP schema.

**Comment by Peter2121** [comment]
> 1- Glewlwyd searches for a LDAP entry based on the login and the filter given with a search pattern like (&(objectClass=organizationalPerson)(cn=bob)) in the Base DB specified.

As I mentioned, the first search of AD arrives **before** I enter any login, I just click on a button "Login"

> Firstly, when I click on "Login" at http://<myip>:4593/app/index.html it tries to search (&(objectClass=organizationalPerson)(cn=g_admin)) in wholeSubtree of my base_search_user.

**Comment by Peter2121** [comment]
> First you can change the config value admin_scope from g_admin to the name of the admin group you use, like Administrators (case sensitive!).
I changed it, still the same thing - no login/password fields shown.

**Comment by babelouest** [comment]
Let me try to rephrase your process so I can try to understand how to solve your problem.

1- You setup your file glewlwyd.conf with your LDAP settings, then run glewlwyd
2- In your browser, clear the cache, local storage and cookies for `myip`, then open the url http://myip:4593/app/ , there you should see the screen below
![not logged in](https://raw.githubusercontent.com/babelouest/glewlwyd/master/screenshots/not_logged_in.png)
3- You click on on the button `Log in` on the top right of this page, you should be redirected to the page http://myip:4593/app/login.html?[parameters] as below
![log in page](https://raw.githubusercontent.com/babelouest/glewlwyd/master/screenshots/sign_in.png)

The LDAP search you mention means that you use the LDAP property `cn` as login and you entered somewhere the username `g_admin` to log.
If you have previously logged in with the user `g_dmin`, you have a cookie set with your login information.
Although, when you open the page `index.html`, there shouldn't be any ldap search if you are not logged in, so it's weird.
If you see a ldap search `(&(objectClass=organizationalPerson)(cn=g_admin))`, when is it? Is it in the step 2 or 3?

**Comment by Peter2121** [comment]
BTW, if I go directly to http://myip:4593/app/login.html - I can login with correct login/password and I cannot login with bad password. The only problem is that I don't see the login, it shows just "You are connected as" without any login name.

**Comment by babelouest** [comment]
Please remove your cookies, local storage and cache from `myip`, then retry to login

**Comment by Peter2121** [comment]
The same thing. Tried with another browser (Chromium) in "Incognito" mode.

**Comment by babelouest** [comment]
I have another idea, your admin application may not have been initialized as a client. How did you initialize your database? Did you use the script `init-*.sql` or the script `glewlwyd.init-db-only*.sql` ?

Check in your database the content of the table `g_scope`, if you see an entry `g_admin`, update the name to your admin scope value, then verify you have an entry in the table `g_client` called 'admin app'. If not, you must apply the script [init-webapp-only.sql](https://github.com/babelouest/glewlwyd/blob/master/docs/database/init-webapp-only.sql)

**Comment by Peter2121** [comment]
I tried the both scripts without any positive result.
My actual config file:
```
port=4593
url_prefix="api"
static_files_path="/usr/share/glewlwyd/webapp"
static_files_prefix = "app"
static_files_mime_types =
(
...
)
allow_origin="*"
log_mode="console"
log_level="DEBUG"
log_file="/tmp/glewlwyd.log"
use_scope=true
refresh_token_expiation=1209600
access_token_expiration=3600
session_expiration=2419200
session_key="GLEWLWYD_SESSION_ID"
admin_scope="Administrateurs"
profile_scope="Utilisa"
code_expiration=600
use_secure_connection=false
secure_connection_key_file="cert.key"
secure_connection_pem_file="cert.pem"
login_url="http://orenbourg:4593/app/login.html?"
grant_url="http://orenbourg:4593/app/grant.html?"
reset_password=false 
reset_password_config = 
{
...
}
hash_algorithm = "SHA256"
 database =
 {
    type               = "sqlite3";
    path               = "/tmp/glewlwyd.db";
 };
authentication =
{
   http_auth                   = false
   http_auth_url               = "http://orenbourg4593/auth/validate"
   http_auth_check_certificate = true
   database_auth            = false
   ldap_auth                = true
   uri                      = "ldap://dc.domain.adm"
   search_scope             = "subtree"
   bind_dn                  = "CN=oauth,CN=Users,DC=domain,DC=adm"
   bind_passwd              = "supersecurepassword"
   base_search_user               = "DC=domain,DC=adm"
   filter_user_read               = "objectClass=organizationalPerson"
   login_property_user_read       = "cn"
   scope_property_user_read       = "memberOf"
   email_property_user_read       = "mail"
   name_property_user_read        = "sn"
   scope_property_user_match      = "contains"
   additional_property_value_read = "memberOf"
   ldap_user_write                 = false
   rdn_property_user_write         = "cn"           
   login_property_user_write       = "cn"           
   scope_property_user_write       = "memberOf"     
   email_property_user_write       = "mail"       
   additional_property_value_write = "memberOf"   
   name_property_user_write        = "sn"
   password_property_user_write    = "userPassword"
   password_algorithm_user_write   = "SSHA"   
   object_class_user_write         = "top,person,organizationalPerson,inetOrgPerson" 
   base_search_client              = "DC=domain,DC=adm"
   filter_client_read                = "objectClass=organizationalPerson"
   client_id_property_client_read    = "cn"
   scope_property_client_read        = "memberOf"
   name_property_client_read         = "sn"
   description_property_client_read  = "description"
   redirect_uri_property_client_read = "labeledURI"
   confidential_property_client_read = "employeeType"
   scope_property_client_match       = "contains"
   ldap_client_write                  = false
   rdn_property_client_write          = "cn"       
   client_id_property_client_write    = "cn"       
   scope_property_client_write        = "memberOf"  
   name_property_client_write         = "sn"      
   description_property_client_write  = "description"
   redirect_uri_property_client_write = "labeledURI" 
   password_property_client_write     = "userPassword"
   confidential_property_client_write = "employeeType"
   password_algorithm_client_write    = "SSHA"  
   object_class_client_write          = "top,person,organizationalPerson,inetOrgPerson" 
}
jwt =
{
...
}
```
My actual database init script:
```
DROP TABLE IF EXISTS `g_refresh_token_scope`;
DROP TABLE IF EXISTS `g_code_scope`;
DROP TABLE IF EXISTS `g_code`;
DROP TABLE IF EXISTS `g_client_user_scope`;
DROP TABLE IF EXISTS `g_client_authorization_type`;
DROP TABLE IF EXISTS `g_resource_scope`;
DROP TABLE IF EXISTS `g_client_scope`;
DROP TABLE IF EXISTS `g_user_scope`;
DROP TABLE IF EXISTS `g_client_scope`;
DROP TABLE IF EXISTS `g_access_token`;
DROP TABLE IF EXISTS `g_refresh_token`;
DROP TABLE IF EXISTS `g_session`;
DROP TABLE IF EXISTS `g_resource`;
DROP TABLE IF EXISTS `g_reset_password`;
DROP TABLE IF EXISTS `g_redirect_uri`;
DROP TABLE IF EXISTS `g_client`;
DROP TABLE IF EXISTS `g_authorization_type`;
DROP TABLE IF EXISTS `g_scope`;
DROP TABLE IF EXISTS `g_user`;
CREATE TABLE `g_user` (
  `gu_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gu_name` TEXT DEFAULT '',
  `gu_email` TEXT DEFAULT '',
  `gu_login` TEXT NOT NULL UNIQUE,
  `gu_password` TEXT NOT NULL,
  `gu_additional_property_value` TEXT,
  `gu_enabled` INTEGER DEFAULT 1
);
CREATE INDEX `i_g_user` ON `g_user`(`gu_id`);
CREATE INDEX `i_g_user_name` ON `g_user`(`gu_name`);
CREATE INDEX `i_g_user_login` ON `g_user`(`gu_login`);
CREATE TABLE `g_scope` (
  `gs_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gs_name` TEXT NOT NULL,
  `gs_description` TEXT DEFAULT ''
);
CREATE INDEX `i_g_scope` ON `g_scope`(`gs_id`);
CREATE INDEX `i_g_scope_name` ON `g_scope`(`gs_name`);
CREATE TABLE `g_authorization_type` (
  `got_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `got_code` INTEGER NOT NULL UNIQUE, -- 0: Authorization Code Grant, 1: Code Grant, 2: Implicit Grant, 3: Resource Owner Password Credentials Grant, 4: Client Credentials Grant
  `got_name` TEXT NOT NULL,
  `got_description` TEXT DEFAULT '',
  `got_enabled` INTEGER DEFAULT 1
);
CREATE INDEX `i_g_authorization_type` ON `g_authorization_type`(`got_id`);
CREATE INDEX `i_g_authorization_name` ON `g_authorization_type`(`got_name`);
CREATE INDEX `i_g_authorization_code` ON `g_authorization_type`(`got_code`);
CREATE TABLE `g_client` (
  `gc_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gc_name` TEXT NOT NULL,
  `gc_description` TEXT DEFAULT '',
  `gc_client_id` TEXT NOT NULL UNIQUE,
  `gc_client_password` TEXT,
  `gc_confidential` INTEGER DEFAULT 0,
  `gc_enabled` INTEGER DEFAULT 1
);
CREATE INDEX `i_g_client` ON `g_client`(`gc_id`);
CREATE INDEX `i_g_client_name` ON `g_client`(`gc_name`);
CREATE INDEX `i_g_client_id` ON `g_client`(`gc_client_id`);
CREATE TABLE `g_redirect_uri` (
  `gru_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gc_id` INTEGER NOT NULL,
  `gru_name` TEXT NOT NULL,
  `gru_uri` TEXT,
  FOREIGN KEY(`gc_id`) REFERENCES `g_client`(`gc_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_redirect_uri` ON `g_redirect_uri`(`gru_id`);
CREATE TABLE `g_resource` (
  `gr_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gr_name` TEXT NOT NULL UNIQUE,
  `gr_description` TEXT DEFAULT '',
  `gr_uri` TEXT
);
CREATE INDEX `i_g_resource` ON `g_resource`(`gr_id`);
CREATE INDEX `i_g_resource_name` ON `g_resource`(`gr_name`);
CREATE TABLE `g_reset_password` (
  `grp_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `grp_username` TEXT NOT NULL,
  `grp_ip_source` TEXT NOT NULL,
  `grp_token` TEXT NOT NULL,
  `grp_enabled` INTEGER DEFAULT 1,
  `grp_issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `grp_reset_at` TIMESTAMP NULL
);
CREATE INDEX `i_g_reset_password` ON `g_reset_password`(`grp_id`);
CREATE INDEX `i_g_reset_password_username` ON `g_reset_password`(`grp_username`);
CREATE TABLE `g_refresh_token` (
  `grt_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `grt_hash` TEXT NOT NULL,
  `grt_authorization_type` INTEGER NOT NULL, -- 0: Authorization Code Grant, 1: Implicit Grant, 2: Resource Owner Password Credentials Grant, 3: Client Credentials Grant
  `grt_username` TEXT NOT NULL,
  `gc_client_id` TEXT,
  `grt_scope` TEXT,
  `grt_issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `grt_last_seen` TIMESTAMP NULL,
  `grt_expired_at` TIMESTAMP NULL,
  `grt_ip_source` TEXT NOT NULL,
  `grt_enabled` INTEGER DEFAULT 1
);
CREATE INDEX `i_g_refresh_token` ON `g_refresh_token`(`grt_id`);
CREATE INDEX `i_g_refresh_token_username` ON `g_refresh_token`(`grt_username`);
CREATE TABLE `g_access_token` (
  `gat_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `grt_id` INTEGER,
  `gat_authorization_type` INTEGER NOT NULL, -- 0: Authorization Code Grant, 1: Implicit Grant, 2: Resource Owner Password Credentials Grant, 3: Client Credentials Grant
  `gat_issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `gat_ip_source` TEXT NOT NULL,
  FOREIGN KEY(`grt_id`) REFERENCES `g_refresh_token`(`grt_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_access_token` ON `g_access_token`(`gat_id`);
CREATE TABLE `g_session` (
  `gss_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gss_hash` TEXT NOT NULL,
  `gss_username` TEXT NOT NULL,
  `gss_issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `gss_last_seen` TIMESTAMP NULL,
  `gss_expired_at` TIMESTAMP NULL,
  `gss_ip_source` TEXT NOT NULL,
  `gss_enabled` INTEGER DEFAULT 1
);
CREATE INDEX `i_g_session` ON `g_session`(`gss_id`);
CREATE INDEX `i_g_session_username` ON `g_session`(`gss_username`);
CREATE TABLE `g_user_scope` (
  `gus_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gu_id` INTEGER NOT NULL,
  `gs_id` INTEGER NOT NULL,
  FOREIGN KEY(`gu_id`) REFERENCES `g_user`(`gu_id`) ON DELETE CASCADE,
  FOREIGN KEY(`gs_id`) REFERENCES `g_scope`(`gs_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_user_scope` ON `g_user_scope`(`gus_id`);
CREATE TABLE `g_client_scope` (
  `gcs_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gc_id` INTEGER NOT NULL,
  `gs_id` INTEGER NOT NULL,
  FOREIGN KEY(`gc_id`) REFERENCES `g_client`(`gc_id`) ON DELETE CASCADE,
  FOREIGN KEY(`gs_id`) REFERENCES `g_scope`(`gs_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_client_scope` ON `g_client_scope`(`gcs_id`);
CREATE TABLE `g_resource_scope` (
  `grs_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gr_id` INTEGER NOT NULL,
  `gs_id` INTEGER NOT NULL,
  FOREIGN KEY(`gr_id`) REFERENCES `g_resource`(`gr_id`) ON DELETE CASCADE,
  FOREIGN KEY(`gs_id`) REFERENCES `g_scope`(`gs_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_resource_scope` ON `g_resource_scope`(`grs_id`);
CREATE TABLE `g_client_authorization_type` (
  `gcat_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gc_client_id` TEXT NOT NULL,
  `got_id` INTEGER NOT NULL,
  FOREIGN KEY(`got_id`) REFERENCES `g_authorization_type`(`got_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_client_authorization_type` ON `g_client_authorization_type`(`gcat_id`);
CREATE TABLE `g_client_user_scope` (
  `gcus_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gc_client_id` TEXT NOT NULL,
  `gco_username` TEXT NOT NULL,
  `gs_id` INTEGER NOT NULL,
  FOREIGN KEY(`gs_id`) REFERENCES `g_scope`(`gs_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_client_user_scope` ON `g_client_user_scope`(`gcus_id`);
CREATE INDEX `i_g_client_user_scope_username` ON `g_client_user_scope`(`gco_username`);
CREATE TABLE `g_code` (
  `gco_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gco_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `gco_code_hash` TEXT NOT NULL,
  `gco_ip_source` TEXT NOT NULL,
  `gco_enabled` INTEGER DEFAULT 1,
  `gc_client_id` TEXT NOT NULL,
  `gco_username` TEXT NOT NULL,
  `gco_redirect_uri` TEXT
);
CREATE INDEX `i_g_code` ON `g_code`(`gco_id`);
CREATE INDEX `i_g_code_username` ON `g_code`(`gco_username`);
CREATE TABLE `g_code_scope` (
  `gcs_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `gco_id` INTEGER NOT NULL,
  `gs_id` INTEGER NOT NULL,
  FOREIGN KEY(`gco_id`) REFERENCES `g_code`(`gco_id`) ON DELETE CASCADE,
  FOREIGN KEY(`gs_id`) REFERENCES `g_scope`(`gs_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_code_scope` ON `g_code_scope`(`gcs_id`);
CREATE TABLE `g_refresh_token_scope` (
  `grts_id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `grt_id` INTEGER NOT NULL,
  `gs_id` INTEGER NOT NULL,
  FOREIGN KEY(`grt_id`) REFERENCES `g_refresh_token`(`grt_id`) ON DELETE CASCADE,
  FOREIGN KEY(`gs_id`) REFERENCES `g_scope`(`gs_id`) ON DELETE CASCADE
);
CREATE INDEX `i_g_refresh_token_scope` ON `g_refresh_token_scope`(`grts_id`);
INSERT INTO g_authorization_type (got_name, got_code, got_description) VALUES ('authorization_code', 0, 'Authorization Code Grant - Access token: https://tools.ietf.org/html/rfc6749#section-4.1');
INSERT INTO g_authorization_type (got_name, got_code, got_description) VALUES ('code', 1, 'Authorization Code Grant - Authorization: https://tools.ietf.org/html/rfc6749#section-4.1');
INSERT INTO g_authorization_type (got_name, got_code, got_description) VALUES ('token', 2, 'Implicit Grant: https://tools.ietf.org/html/rfc6749#section-4.2');
INSERT INTO g_authorization_type (got_name, got_code, got_description) VALUES ('password', 3, 'Resource Owner Password Credentials Grant: https://tools.ietf.org/html/rfc6749#section-4.3');
INSERT INTO g_authorization_type (got_name, got_code, got_description) VALUES ('client_credentials', 4, 'Client Credentials Grant: https://tools.ietf.org/html/rfc6749#section-4.4');
INSERT INTO g_scope (gs_name, gs_description) VALUES ('Administrateurs', 'Glewlwyd admin scope');
INSERT INTO g_scope (gs_name, gs_description) VALUES ('Utilisa', 'Glewlwyd profile scope');
INSERT INTO g_client (gc_name, gc_description, gc_client_id) VALUES ('admin app', 'Glewlwyd administration app', 'Administrateurs');
INSERT INTO g_redirect_uri (gru_name, gru_uri, gc_id) VALUES ('uri_g_admin', '../app/index.html', (SELECT gc_id from g_client WHERE gc_client_id='Administrateurs'));
INSERT INTO g_client_authorization_type (gc_client_id, got_id) VALUES ('Administrateurs', (SELECT got_id from g_authorization_type WHERE got_name='code'));
INSERT INTO g_client_authorization_type (gc_client_id, got_id) VALUES ('Administrateurs', (SELECT got_id from g_authorization_type WHERE got_name='token'));

```
With the actual config I cannot access admin app neither authenticate me on `login.html` page.

**Comment by AlroneRhyn** [comment]
Hi Guys,

Using Azure now. Regards
