### ISSUE TITLE
webapp not working

### ISSUE THREAD

**Issue by yandoogle** [babelouest/glewlwyd#57]
Hi Nicolas!
I am unable to use Glewlwyd admin page with the following error:

![изображение](https://user-images.githubusercontent.com/1921271/60707307-79085280-9f1c-11e9-886b-dbea4e5e1e66.png)

Can you help me with it?

Glewlwyd version 2.0.0-b1 on Devuan 9.

My configuration:

glewlwyd.conf
port=4593
external_url="http://localhost:4593"
login_url="login.html"
url_prefix="api"
static_files_path="/usr/share/glewlwyd/webapp"
allow_origin="*"
log_mode="console"
log_level="DEBUG"
session_expiration=2419200
session_key="GLEWLWYD2_SESSION_ID"
admin_scope="g_admin"
profile_scope="g_profile"
user_module_path="/usr/local/lib/glewlwyd/user"
client_module_path="/usr/local/lib/glewlwyd/client"
user_auth_scheme_module_path="/usr/local/lib/glewlwyd/scheme"
plugin_module_path="/usr/local/lib/glewlwyd/plugin"
use_secure_connection=false
hash_algorithm = "SHA512"
database =
{
  type = "mariadb"
  host = "localhost"
  user = "glewlwyd"
  password = "glewlwyd"
  dbname = "glewlwyd"
  port = 0
}

config.json
{
  "GlewlwydApiUrl": "http://localhost:4593",
  "ProfileUrl": "http://localhost:4593/profile.html",
  "AdminUrl": "http://localhost:4593/index.html",
  "LoginUrl": "http://localhost:4593/login.html",
...

Thanks!

**Comment by babelouest** [comment]
Hello @yandoogle , thanks for the issue.

I think it's simple-but-dummy bug from me on the `glewlwyd.conf` file that I fixed earlier. I missed to add the json format in the static files mime types...

To fix this, open your glewlwyd.conf file, add the following block in the `static_files_mime_types` array (at the end of the glewlwyd.conf file):

```
  {
    extension = ".json"
    mime_type = "application/json"
  },
```

If this doesn't fix your problem, let me know, I'll dig deeper.

**Comment by yandoogle** [comment]
Thanks for your quick response, @babelouest.

I tried to add these lines to configuration file earlier because the glewlwyd server reported about absent application/json mime_type directly. 
Unfortunately, this does not solve my problem.

**Comment by babelouest** [comment]
And that's another round on me!

In the provided `webapp/config.json.sample` file, the first parameter key is `GlewlwydApiUrl`, it has been renamed lately to `GlewlwydUrl` but I forgot to push the changes in the sample file.

Thanks again @yandoogle !

**Comment by yandoogle** [comment]
Yes it is.
@babelouest thanks again and good luck in the development of a great project!

**Comment by babelouest** [comment]
Thanks!

Don't hesitate to open new issues if you found other problems or if you have other questions.
